kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: repository-claim
spec:
  accessModes:
    {{- if (gt (.Values.octopus.replicaCount | int) 1)}}
    - ReadWriteMany
    {{- else }}
    - {{.Values.persistence.storageAccessMode}}
    {{- end }}
  {{- if (eq "-" (.Values.persistence.storageClassName | toString)) }}
  storageClassName: ""
  {{- else if .Values.persistence.storageClassName }}
  storageClassName: "{{ .Values.persistence.storageClassName }}"
  {{- end }}
  resources:
    requests:
      storage: {{.Values.persistence.repositoryVolumeSize}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifacts-claim
spec:
  accessModes:
    {{- if (gt (.Values.octopus.replicaCount | int) 1)}}
    - ReadWriteMany
    {{- else }}
    - {{.Values.persistence.storageAccessMode}}
    {{- end }}
  {{- if (eq "-" (.Values.persistence.storageClassName | toString)) }}
  storageClassName: ""
  {{- else if .Values.persistence.storageClassName }}
  storageClassName: "{{ .Values.persistence.storageClassName }}"
  {{- end }}
  resources:
    requests:
      storage: {{.Values.persistence.artifactVolumeSize}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: task-logs-claim
spec:
  accessModes:
    {{- if (gt (.Values.octopus.replicaCount | int) 1)}}
    - ReadWriteMany
    {{- else }}
    - {{.Values.persistence.storageAccessMode}}
      {{- end }}
  {{- if (eq "-" (.Values.persistence.storageClassName | toString)) }}
  storageClassName: ""
  {{- else if .Values.persistence.storageClassName }}
  storageClassName: "{{ .Values.persistence.storageClassName }}"
  {{- end }}
  resources:
    requests:
      storage: {{.Values.persistence.taskVolumeSize}}